rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails4_0.gemfile
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/rails4_0.gemfile

