# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
language: ruby
cache:
- bundler
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - ruby-head
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  include:
  - rvm: 2.2.6
    gemfile: gemfiles/rails_4_1.gemfile
  - rvm: 2.3.3
    gemfile: gemfiles/rails_4_1.gemfile
