language: ruby
cache:
- bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
gemfile:
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
