# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
language: ruby
cache:
- bundler
rvm:
  - 2.0
  - 2.1.10
  - 2.2.6
  # Since the Travis Build Env does not recognize `2.3` alias yet
  # We need to specify the version precisely
  - 2.3.3
  - ruby-head
gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
